spring:
  profiles:
    group:
      "dev": "oauth, jwt"
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1541
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s

logging:
  level:
    root: DEBUG
