spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myDb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
            scope:
              - profile_image
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri:
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id